version: '3.8'

services:
  # Podcastoor Processor
  processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: podcastoor-processor
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NODE_ENV=development
      - CONFIG_PATH=/app/config
      - STORAGE_BASE_DIR=/app/storage
      - STORAGE_PUBLIC_URL=http://localhost:3000/files
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:3000}
    volumes:
      - ./config:/app/config:ro  # Required: config directory with config.yaml
      - ./data:/app/data
      - ./tmp:/app/tmp
      - ./storage:/app/storage
    ports:
      - "3000:3000"
    restart: unless-stopped