version: '3.8'

services:
  # MinIO for local S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: podcastoor-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO Client to create bucket on startup
  minio-setup:
    image: minio/mc:latest
    container_name: podcastoor-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 minioadmin minioadmin123;
      mc mb minio/podcastoor --ignore-existing;
      mc policy set public minio/podcastoor;
      echo 'MinIO setup complete';
      "

  # Podcastoor Processor
  processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: podcastoor-processor
    depends_on:
      minio-setup:
        condition: service_completed_successfully
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - STORAGE_ACCESS_KEY=minioadmin
      - STORAGE_SECRET_KEY=minioadmin123
      - NODE_ENV=development
      - CONFIG_PATH=/app/config
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
      - ./tmp:/app/tmp
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  minio_data:
    driver: local