name = "podcastoor-worker"
main = "dist/index.js"
compatibility_date = "2023-12-01"
node_compat = true

[env.production]
name = "podcastoor-prod"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "podcastoor-staging"
vars = { ENVIRONMENT = "staging" }

[[kv_namespaces]]
binding = "RSS_CACHE"
preview_id = "your-preview-kv-id"
id = "your-production-kv-id"

[[r2_buckets]]
binding = "AUDIO_STORAGE"
bucket_name = "podcastoor"
preview_bucket_name = "podcastoor-preview"

[vars]
PROCESSOR_URL = "https://processor.podcastoor.com"
CACHE_TTL = "300"